### ISSUE TITLE
The ExpandMacroAsync method formats the 'd' case incorrectly

### ISSUE THREAD

**Issue by horch004** [alexreinert/ARSoft.Tools.Net#25]
When the spf record below is validated the %{d} parts gets an additional dot which invalidates the resulting domain name. The DomainName.Parse method throws an exception.

`v=spf1 include:%{ir}.%{v}.%{d}.spf.has.pphosted.com -all`

The issue is the `case "d"` at line 556. More precisely line 557. The domain.ToString() returns a domain name with a dot prefix. This causes two dots and invalidates the resulting string.

**Comment by alexreinert** [comment]
Fixed in version 3.1.1

**Comment by lukos** [comment]
Please can you link to where the change was made? We can't upgrade to v3 because it is .net 6 only and we are on netstandard so will need to backport the fix.

Thx
