### ISSUE TITLE
DnsClient.Default.Resolve is returing null in server, even though we got the result in public dns lookup 

### ISSUE THREAD

**Issue by somratcste** [alexreinert/ARSoft.Tools.Net#26]
We got null return in server for some cases. 
But when I have tested in my local with the same domain and same functionality we got the result always. 
For the same domain, I have also checked here: https://dnschecker.org/ It looks fine. 

DnsMessage dnsMessage = DnsClient.Default.Resolve(DomainName.Parse("google.com"), RecordType.Txt) // returns null in server some times

Using Version: "2.2.9" 
.Net Version: v4.7.2

**Comment by somratcste** [comment]
Yes, it does

**Comment by alexreinert** [comment]
Please provide a wireshark dump where the problem occurs.

**Comment by somratcste** [comment]
Could you please explain a little bit what do you need to know?

**Comment by alexreinert** [comment]
I need a dump of the DNS network traffic, this can be done using Wireshark.

**Comment by somratcste** [comment]
I can't share this kind of information.

**Comment by alexreinert** [comment]
Then I cannot help you. I checked it, there is no general issue, so it needs to be debugged if the packages are correct on the network or if there is an issue with the DNS server or on network level.

**Comment by alexreinert** [comment]
You could try to not use the DnsClient.Default but an defined DNS like the Google DNS using a custom DnsClient instance.

**Comment by somratcste** [comment]
I appreciate your assistance and response, @alexreinert. Unfortunately, I am unable to provide additional information, which makes it difficult to identify any potential security breach on your end. However, I have found an alternative solution and am satisfied with closing the matter.
