### ISSUE TITLE
HTTPS and SVCB support

### ISSUE THREAD

**Issue by rage4** [alexreinert/ARSoft.Tools.Net#27]
Hello

Would you be able to add the HTTPS and SVCB record types? We can expect the RFC this year, but the records are in use since 2020.

Cheers

**Comment by alexreinert** [comment]
Is already on the map and will be included in one of the next releases.

**Comment by rage4** [comment]
Excellent, any ETA?

**Comment by alexreinert** [comment]
Soon, but there is no fixed date.

**Comment by alexreinert** [comment]
Support is now available in version 3.2.0
