### ISSUE TITLE
Use a port different than port 53 for DNS Server

### ISSUE THREAD

**Issue by carlos-sarmiento** [alexreinert/ARSoft.Tools.Net#30]
I'm trying to setup the DnsServer class and I don't see a way to pass the Port I want the server to run on to either `TCPTransport` or `UDPTransport`. Looking at the code, it seems the value is hardcoded for 53. 

Is it possible to add a new parameter to the constructor so the port can be customized?

**Comment by alexreinert** [comment]
Both, UdpServerTransport and TcpServerTransport, have a constructor with an IPEndpoint, which can be used for that.

**Comment by carlos-sarmiento** [comment]
I'm sorry, it seems my brain decided to forget how to read Constructor declarations in C#. Found the method you are referring to. 

The library is pretty amazing, thanks for writing it.

Now I'll see myself out....
