### ISSUE TITLE
.NET Core: System.Private.Networking

### ISSUE THREAD

**Issue by Schaussi** [alexreinert/ARSoft.Tools.Net#4]
Hi,

with the current version I get an error when using a .NET Core / Standard project (translated):

>Package System.Private.Networking 4.0.0 not compatible with netcoreapp2.0  (.NETCoreApp,Version=v2.0)/win10-x64. System.Private.Networking 4.0.0 supports:
>   - dnxcore50 (DNXCore,Version=v5.0)
>   - netcore50 (.NETCore,Version=v5.0)

Is there maybe a workaround for this, e.g. a newer preview version for this package?
Thank you

Edit:
Nevermind, error disappeared when creating a new .NET Standard project solution for the library.

**Comment by btastic** [comment]
Hello,

I am getting the same error. I don't have the option to change the project solution to .NET Standard.

Any idea how to get this library working with .NET Core 2.0?

Thanks

**Comment by Schaussi** [comment]
I have created a fork here: https://github.com/DXSdata/ARSoft.Tools.NetStandard
Should also work with .Net Core projects.
