### ISSUE TITLE
.NETCore 2.0 build

### ISSUE THREAD

**Issue by shar0119** [alexreinert/ARSoft.Tools.Net#6]
Would it be possible to create a .NETCore 2.0 build?

**Comment by shar0119** [comment]
I was able to build it for .NET Core 2.0 but I had to make the following two changes and will try to test the areas that this affects. But otherwise, I was able to build it just fine.

`private static readonly SecureRandom _secureRandom = new SecureRandom(new CryptoApiRandomGenerator());`

to 

`private static readonly SecureRandom _secureRandom = new SecureRandom(new VmpcRandomGenerator());`

AND

`selectedBytes = SubjectPublicKeyInfoFactory.CreateSubjectPublicKeyInfo(DotNetUtilities.FromX509Certificate(certificate).GetPublicKey()).GetDerEncoded();`

to

`selectedBytes = SubjectPublicKeyInfoFactory.CreateSubjectPublicKeyInfo(PublicKeyFactory.CreateKey(certificate.GetPublicKey())).GetDerEncoded();`

**Comment by ststeiger** [comment]
You could have spared you the work. 
I ported it a long time ago, to .NET Core 1.Whatever
Here: https://github.com/ststeiger/Arsoft

**Comment by shar0119** [comment]
Thank you, that helps out a lot!
